### ISSUE TITLE
Suggestions!

### ISSUE THREAD

**Issue by mahendratyagi** [evias/blockchain-cli#2]
Hi @evias ,

I like your solution so much  in case when we go integrate the usdt node js other libs. So here as I have seen your code there is method getColoredScript so inside that method you have this below line  
$rawOperation = $this->arguments["colored-op"] ?: "6f6d6e69000000000000001f000000002faf0800";
So could you please suggest $this->arguments["colored-op"] => what is the value of it and where from you are getting, not sure what exactly is this. Also what is the 6f6d6e69000000000000001f000000002faf0800 ?

I am also trying to add op_return to the bitcoin multisig trasaction for usdt. So your help will help me a lot. Thanks

**Comment by mahendratyagi** [comment]
Actually I have multisig transaction object of copay that uses Bitcoin protocol so I need to add op_return to that trasaction, But here I am not sure what should be the hex value so that I can use that as op_return. So could you please help me on that.
Since as your code you have put it static 6f6d6e69000000000000001f000000002faf0800 so I strongly keen to know how did you generated it? So that I can use that data to generate the same.

**Comment by evias** [comment]
Hello there,

This is the hexadecimal hash of the OP_RETURN operation being carried out by your input. Let me explain how this works: 

- Omni publishes info on the bitcoin blockchain in form of low-amount Inputs with an OP_RETURN operation
- This OP_RETURN operation only specifies the *amount* so it is OK to just copy it in a new Input (for sending those coins)

What Omni does is following: 

- It defines the new RECIPIENT of the colored coins by a simple rule, as you can see in following links: 

- https://bitcointalk.org/index.php?topic=2500531.msg25868201#msg25868201

> The receiver is chosen/indicated by the last output address that is not the sender.

Hope this is some better information ! :) What you need to do is to copy the OP_RETURN hexadecimal payload from the Input you are trying to spend :)

For the record, I named this "colored-op" because it is in fact the `Colored Operation` as it specifies the amount of colored coins that will be sent to the latest output which is not the sender.

✌️

**Comment by mahendratyagi** [comment]
Hi @evias Thanks for your help :)
So I shall Just copy of the coins/amount from the input and send it in OP_RETURN payload?
Also my current transaction is looking like as below so please let me know is this correct?
{
    "addresses": [
        "2NBP3G9sf9s8xjq4vPSrGUnSSdz3tBxGxd2"
    ], 
    "block_height": -1, 
    "block_index": -1, 
    "confirmations": 0, 
    "data_protocol": "unknown", 
    "double_spend": false, 
    "fees": 356, 
    "hash": "95628fd8dd8cb4c65ad56d905140c7406832fc9f71fe9c5c969459a82bb0f869", 
    "inputs": [
        {
            "addresses": [
                "2NBP3G9sf9s8xjq4vPSrGUnSSdz3tBxGxd2"
            ], 
            "age": 1324615, 
            "output_index": 0, 
            "output_value": 1015625, 
            "prev_hash": "5791ae73cc7e06982b1b794f9a97f72d301150c41b3cf6daf4c6633052c73e3a", 
            "script": "004752210251a422018ab3f16c0db732af7152f0934023883d2138369d1b7a73163f0dc2a62102ca97efa55def7ca2de8456c74daef5df469c1bc3cd3f7e5470b0832215dda84752ae", 
            "script_type": "pay-to-script-hash", 
            "sequence": 4294967295
        }
    ], 
    "outputs": [
        {
            "addresses": null, 
            "data_hex": "4f505f52455455524e20313720307836663664366536393330333033333331333833303330333033303330333033303330", 
            "data_string": "OP_RETURN 17 0x6f6d6e6930303331383030303030303030", 
            "script": "6a314f505f52455455524e20313720307836663664366536393330333033333331333833303330333033303330333033303330", 
            "script_type": "null-data", 
            "value": 0
        }, 
        {
            "addresses": [
                "2NBP3G9sf9s8xjq4vPSrGUnSSdz3tBxGxd2"
            ], 
            "script": "a914c6eca34b6d6c4b94fdf1505ce57d2f0b5b2b490f87", 
            "script_type": "pay-to-script-hash", 
            "value": 101562
        }, 
        {
            "addresses": [
                "2NBP3G9sf9s8xjq4vPSrGUnSSdz3tBxGxd2"
            ], 
            "script": "a914c6eca34b6d6c4b94fdf1505ce57d2f0b5b2b490f87", 
            "script_type": "pay-to-script-hash", 
            "value": 913707
        }
    ], 
    "preference": "low", 
    "received": "2018-06-15T10:46:27.408307016Z", 
    "relayed_by": "54.82.15.250", 
    "size": 248, 
    "total": 1015269, 
    "ver": 1, 
    "vin_sz": 1, 
    "vout_sz": 3
`} 
The OP_RETURN payload is omni+version+sendtransaction+amount/coin

**Comment by evias** [comment]
Yes you are right, I summarized a bit and actually it was wrong to say "it's only the amount", as it obviously also contains the version, function and currency details.

I cannot really confirm your data, what I can tell you is the following steps run-through :

- 1) Find the OP_RETURN operation that is currently stored on a Bitcoin address (the hexadecimal hash after `OP_RETURN`)

- 2) Find the details of that input (hash, address, private key)

- 3) Check the exact *recipient* of the Omni funds (as mentioned earlier, "interpret" the recipient as would Omni), this with the following precision : 

> The receiver is chosen/indicated by the last output address that is not the sender.

- 3') This means that you would check the transaction in which you copied the OP_RETURN and get the last output address (which is not the sender) from there. Because that is the address which owns the funds on the Omni network.

- 4) Now that you have those details you can simply create a new address with omni wallet and `reproduce a sendtransaction call` which means that you would reference the found out **input** , include the correct script solution for the current recipient, and add 2 new outputs.

- 5.1) First new output would be the OP_RETURN copy
- 5.2) If you plan to use an address with lots of BTC, introduce a change address here
- 5.3) Add the ending recipient of your funds with a btc spend transaction

I hope this helps :) I listed all the tools needed in this also in the README

✌️
